vuejs/vue-class-component

- index.js
clone value if it's `null`
otherwise throws an exception `Uncaught TypeError: Can not convert undefined or null to object`
> clone value if it's null

- index.js
to create the components that do not need such options as a template, props, replace, etc
This is useful when mounting component to the existing DOM-element and it already contains a template with the expressions and need only data, methods, computer and hooks
eg
```js
import Component from 'vue-class-component'
@Component
class Some {
data () {
...
}
someHandler() {
...
}
get someComputed() {
...
}
}
```
> Added the ability to decorate without options

- index.d.ts
To accept multiple constructors for `type` in prop option.
> Update prop option type for Vue 1.0.21+

- .gitignore
- README.md
- circle.yml
- example/example.ts
- example/tsconfig.json
- example/webpack.config.js
- index.d.ts
- index.ts
- package.json
- test/test.ts
- test/tsconfig.json
- test/webpack.config.js
- tsconfig.json
I think it would be better to write the code of this project in TypeScript due to high affinity with user land TypeScript code.
We don't have to write declaration files since TS compiler will generate them automatically.
In this PR, I've rewrite `index.js` to `index.ts` with adding type annotations, also replace `Component.name` with `Component._componentTag`. (In my understood, there is no `Component.name` in Vue 2.0?)
How would you feel about this?
> Migrate to TypeScript

- .gitignore
- example/example.ts
- package.json
- src/component.ts
- src/declarations.ts
- src/index.ts
- test/test.ts
- tsconfig.json
I've moved and divide `index.ts` to `src/` and also changed the output directory of TS files to `lib/` for further development.
I'll open one more PR for adding a new feature if this is merged.
> Move source code to src

- README.md
- example/example.ts
- src/component.ts
- src/data.ts
- test/test.ts
This PR enable to declare initial data as class properties for components. This let us define Vue component more native class-like style.
Example:
```js
@Component({
props: ['foo']
})
class MyComp extends Vue {
bar = 123
baz = this.foo
}
```
...will be converted into:
```js
{
props: ['foo'],
data () {
return {
bar: 123,
baz: this.foo
}
}
}
```
> Enable to collect inital class properties as vue instance data

- README.md
- src/component.ts
- src/data.ts
- src/index.ts
- src/util.ts
- test/test.ts
**This PR depends on #29, please see #29 before seeing this**
This PR adds `createDecorator` helper to let us create custom decorators for class-style vue components. The helper expects a callback function as the 1st argument and the callback will receive a component options object. So, we can easily create Vue component-specific decorators.
Example:
```js
import Component, { createDecorator } from 'vue-class-component'
export const NoCache = createDecorator((options, key) => {
options.computed[key].cache = false
})
@Component
class MyComp extends Vue {
// the computed property will not be cached
@NoCache
get random () {
return Math.random()
}
}
```
> Provide a helper to create custom decorators

- package.json
- src/component.ts
- test/.babelrc
- test/test-babel.js
- test/webpack.config.js
Related to #29 
If we use Babel, an error will be occurred during collecting data. Because Babel checks whether `this` is instance of the actual class or not and the dummy object does not inherit component class actually.
I've tweak the extend part to use the `extend` method belongs to the component class instead of super class.
I've also added test cases for Babel environment.
> Fix an error during collecting data in case of using Babel

- src/component.ts
- src/data.ts
This PR fixes #33.
Some errors will be occurred if we use JavaScript native class since it does not allow updating `prototype` and must be called with `new` keyword.
I've revert the code of extending component constructor and change the approach to collect class properties...
> Compatibility with native class

- src/data.ts
- test/test-babel.js
In the environment of Babel + Decorator, decorated class properties are treated as enumerable even if we does not set initial value. That causes unexpected initialization of data, reported on #31 
I've just added `undefined` check in the data collection process.
> should not collect uninitialized class properties

- example/example.ts
- example/webpack.config.js
- package.json
- test/webpack.config.js
- Fix breaking change for [webpack@2.1.0-beta.26](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.26)
- Add rimraf for windows support
> webpack to beta.27; rimraf for cross platform support

- README.md
- package.json
- src/data.ts
- src/globals.d.ts
- src/util.ts
- test/test-babel.js
As reported in #41, we cannot interpolate constructor without inheritance. So I think printing warning is appropriate on this situation.
/ping @yyx990803
> Print warning if class property is used without inheriting Vue class

- README.md
- example/example.html
- example/example.ts
- example/webpack.config.js
- package.json
Close #44 
@HerringtonDarkholme Can you check this? :)
> Adjust TypeScript example

- README.md
- src/component.ts
- src/index.ts
- test/test.ts
This feature allows us to register additional hooks for class components like Vue Router's `beforeRouteEnter`.
Close #38
> Add registerHooks method to Component decorator

- build/build.js
- build/release.sh
- package.json
- test/test-babel.js
- test/test.ts
- tsconfig.json
> Add build script for UMD and minified UMD builds

- README.md
- example/App.vue
- example/example.html
- example/example.ts
- example/sfc.d.ts
- example/webpack.config.js
- package.json
This PR updates the examples in this repo to use single file component (`.vue` file), and also include webpack configuration for that. It would be more helpful to see how to use vue-class-component.
> Rewrite the examples with single file component

- README.md
As pointed out on #67, we may need to mention about caveats of class property definition. I've added it in docs on this PR.
> update readme for caveats of class properties

- src/component.ts
- test/test.ts
- test/webpack.config.js
Just make it simple to give names to components
> Use class name as Vue component's name

- README.md
> add class property caveat in readme

- example/sfc.d.ts
I'm not sure why/when this declaration does not work. It seems to should be `export default Vue` rather than `export default typeof Vue` now.
/ping @HerringtonDarkholme @kaorun343 
Fix #123
> chore(example): update sfc declaration

- README.md
**vue-router** v2.2+ has new lifecycle event called `beforeRouteUpdate` ([documentation](https://router.vuejs.org/en/advanced/navigation-guards.html#in-component-guards)). This commit adds corresponding change to README file with added hook so that new users are able to use it.
> Update README.md to support beforeRouteUpdate hook

- example/tsconfig.json
- package.json
- src/component.ts
- src/data.ts
- src/declarations.ts
- src/index.ts
- src/util.ts
- test/test.ts
- tsconfig.json
- yarn.lock
**Please do not merge this until https://github.com/vuejs/vue/pull/6391 is merged**
This PR is for adapting to the new Vue typings. It should behave as same as before other than typings.
Note that it still uses the fork as a dependency. I'll update it when vuejs/vue#6391 is merged and released.
/cc @HerringtonDarkholme @kaorun343 @yyx990803
> feat: adapt to the new vue typings

- src/util.ts
- test/test-babel.js
- test/test.ts
fix #155 
Previously, `createDecorator` is not considered to be used for creating a custom class decorator. For this change, we now allows the users to create it officially.
I also changed the `createDecorator`'s type annotation because function overload cannot infer the factory function type.
/ping @HerringtonDarkholme @kaorun343
> fix: allow to create a custom class decorator

- README.md
- example/App.vue
- example/Hello.vue
Add children component in example and tell devs how to use it.
Fix https://github.com/vuejs/vue-class-component/issues/94
> chore(example): add child component

- src/component.ts
Fix #181 
TS 2.6 seems to change `Object.getOwnPropertyDescriptor`
Note `key` is already the property name, there is no need to check null in runtime.
> fix: fix nullable type in ts 2.6

- src/data.ts
- test/test-babel.js
Currently, Babel decorators cannot define `props` and `methods` because it tries to reconfigure proxied properties, then `Cannot redefine property` error is thrown.
This fix allows the users to create property decorators that declare props/methods in Babel.
This does not solve the difference between babel and ts decorator behaviors but I think it does not matter that users make their own custom decorator with caution.
> fix: allow to reconfigure proxied properties in data hook

- src/index.ts
If you want to create a non-parameterized decorator you need to something like:
````ts
const newDecorator = const createDecorator((componentOptions, k) => { ...});
````
But that will give you the following error:
> Exported variable 'newDecorator' has or is using name 'VueDecorator' from external module
> Add VueDecorator to named exports

- src/component.ts
- test/test-babel.js
- test/test.ts
Static methods are defined as non-enumerable properties in Babel, so Babel users cannot use static methods.
I've changed the implementation with `getOwnPropertyNames` and use the original property descriptor on defining the property on the extended constructor.
This also changes the extended constructor's `name` and `length` property. But it probably does not affect user's code.
fix #186
> fix: forward static functions in babel

- src/component.ts
- src/util.ts
- test/test.ts
fix #192 
Since IE <= 10 does not have `__proto__`, TypeScript just assigns the static properties of the super class in such environment. It causes the problem in static member forwarding.
The problem is the inherited properties are declared as same manner as the sub class property. Then the super component options (`Ctor.options`) are also enumerated in forwarding process and accidentally overwrite the extended Vue constructor.
To avoid this behavior, we can check equality of the reference of super class property and sub class property. If they are the same, we can say the property is inherited property.
Unfortunately, primitive values cannot be checked by this approach because the users may declare the same named properties with the same value. So I leave them to always forward for …
> fix: avoid to overwrite component options on IE <= 10

- src/data.ts
The overwriting `_init` function causes memory leak because it retains the `vm` instance even after the `data` hook is finished. The `_init` function itself is also kept with the original component class. So we need to free the overwriting `_init` function after it is used.
fix #209
> fix: fix memory leak of detached DOM tree

- example/tsconfig.json
- src/data.ts
- test/tsconfig.json
- tsconfig.json
This PR updates tsconfigs in this repo.
* removed `experimentalDecorators` in base config since the lib itself does not use decorators.
* removed `removeComments` since they are eliminated in minification in any cases.
* use `extends` in tsconfig for test codes.
* added `noUnusedLocals` and `noUnusedParameters`.
* switched to `es2015` for `module` option in tsconfig for example code.
> chore: tidy up tsconfig.json

- example/tsconfig.json
Hello, this pr resolves a bug caused by compiler option "jsx" which compiles file incorrectly. "react" option compiles to `.js` file using `React.createElement()` which does not work in some cases (e.g. cannot pass Prop from parent VNode correctly in jsx tag.). A better way is using "preserve" option compile `.tsx` to `.jsx` and then use babel to transform.
> change compiler option "jsx";

- example/App.vue
I've updated the TypeScript example based on [this comment](https://github.com/vuejs/vue-class-component/issues/220#issuecomment-381557825) (thanks @KaelWD!) which eliminates redundant type definition for `props`. I guess this is a better way for TypeScript users since the `props` types are inferred by its `props` option unlike decorator approach.
/cc @HerringtonDarkholme @kaorun343
> docs: separate props definition to make their types be inferable

- README.md
Call next() inside vue-route hooks (i.e beforeRouteEnter and beforeRouteLeave) to confirm navigation otherwise route is not rendered.
> Updated README. Call next() inside vue route hook to confirm navigation

- src/component.ts
- test/test-babel.js
- test/test.ts
should collect class properties which decorated by 3rd typescript written decorators library.
Check the added unit tests for details :)
> bugfix: collect decorated class properties

- README.md
The mixin is exported as a named export but used as a default export.
> Fix README mixin usage

- src/reflect.ts
To be honest: I am not 100% certain that this change is good because it may simply hide an incorrect configuration on the part of the developer. However since there is already a check in place for the existence of `Reflect` adding a check for `Reflect.getOwnMetadataKeys` may also be warranted.
> fix: adds check forReflect.getOwnMetadataKeys

- src/component.ts
Adding `serverPrefetch` to the list of internal methods for the vue class component. This is a new hook that lets you fetch data on the server for server side rendering.
https://ssr.vuejs.org/api/#serverprefetch
> [feat] Add serverPrefetch method from Vue 2.6

- build/build.js
- package.json
This proposed change adds a ES6 module output to the build, for use with ES6 module-aware bundlers such as rollup.
> Build output ES6 module version

- src/component.ts
- src/reflect.ts
In [this commit](https://github.com/vuejs/vue-class-component/pull/284/commits/8022c7a59a35034a3f6b31310360e195fd9d4103), `reflectionIsSupported` has been refactored from `(Reflect && Reflect.defineMetadata) !== undefined` to `typeof Reflect !== undefined && Reflect.defineMetadata`.
But also, from decorator runtime (function) check to one-time check on `import` (var). Which caused a small issue:
I've faced a situation, where one of my dependencies brings `reflect-metadata` as it's own dependency, and being imported after `vue-class-component` package.
When decorating is applied, metadata already treated as unsupported and metadata is lost.
The only way to solve this is to import `reflect-metadata` before our main `App` module (in other words, before decorated are applied).
But in my case, …
> check reflectionIsSupported in decorator runtime

- README.md
- src/index.ts
- src/lifecycle.ts
> feat: add lifecycle types into vue instance type

- package.json
Adding `sideEffects: false` helps webpack to tree-shake the user code includes vue-class-component.
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
> feat: mark as side effect free to enable efficient tree-shaking

- .gitpod.yml
- README.md
Hello. :slightly_smiling_face: 
This Pr makes contributions easier by fully automating the dev setup with Gitpod(a full-featured online IDE) which is free for OSS. With one click it'll start a workspace and automatically:
- clone the `vue-class-component` repo.
- install the dependencies.
- run `yarn dev`.
- run `yarn docs:dev`.
so that anyone interested in contributing can start straight away without any friction.
You can give it a try on my fork of the repo via the following link:
https://gitpod.io/#https://github.com/nisarhassan12/vue-class-component
This is how it looks:
> easier contributions.

- docs/.vuepress/config.js
- docs/guide/annotate-component-type-in-decorator.md
This PR adds a new docs section that describes how to annotate `this` type on functions in the decorator.
```ts
@Component<Post>({ // <---
watch: {
postId(id: string) {
this.fetchPost(id)
}
}
})
class Post extends Vue {
postId: string
fetchPost(postId: string): Promise<void> {
// ...
}
}
```
> docs: add a guide to annotate component type in decorator

- src/util.ts
> fix: make mixins helper type compatible with previous usage

- .circleci/config.yml
- package.json
Upgrade the version of `node` and `vue-loader` to solve the CI error. 
In addition, I would like to ask whether you consider integrating Github Action into the project?
> Upgrade the version of node and vue-loader to solve the CI error.

- README.md
Had a hard time to find info on @Options decorator. Please consider adding this to spare other users some time.
> add note for missing v8 docs
